export const TEXT_MAP = {
ar: {
    heading: 'عن',
    content: '我的名字是 David Partyka 博士，我創建了 Quake Catalog UI。儘管我接受了多年的化學家培訓，甚至從頂尖大學獲得了博士學位，並發表了20 多篇論文，但在我工作的最後一家工程公司（主要專注於化學）於2011 年倒閉後，我轉向了Web 開發。我進行職業轉型是為了獲得更好的就業和工作與生活平衡的機會，多年後，我全心全意地相信這是正確的選擇。<br /><br />&emsp;أشعر أنني في وضع فريد تقريبًا حيث يمكنني الآن استخدام مهاراتي العلمية والتحليلية لتطوير مواقع الويب (مثل أداة تحليل CSS الخاصة بي، <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) التي لن يتمكن الأشخاص الآخرون، أو حتى الفرق، من تنفيذها بكفاءة من حيث التكلفة الإنتاج لأن مثل هذه المواقع تتطلب موظفين متعددين يتمتعون بمجموعات مهارات مختلفة. <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">Earthquake Hazards Program API</a>，查詢包含數百年歷史的資料庫地震數據提供了這樣一個機會。儘管此程式是極少數為 API 提供使用者介麵包裝的程式（發現 <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">此處</a> ），使API 的訪問變得更加容易，仍然可以添加多個增值增強功能，包括多種語言的訪問（截至2024 年1 月的英語、西班牙語、法語和意大利語） 。這就是我開發的 Quake Catalog UI 的目標。'
  },
  de: {
    heading: 'Um',
    content: 'Mein Name ist Dr. David Partyka und ich habe die Quake Catalogue UI erstellt. Obwohl ich mehrere Jahre als Chemiker ausgebildet war, sogar an einer Spitzenuniversität promovierte und über 20 Artikel veröffentlichte, wechselte ich zur Webentwicklung, nachdem das letzte Ingenieurbüro, für das ich gearbeitet hatte (das sich stark auf Chemie konzentrierte), im Jahr 2011 zusammenbrach. Ich habe diesen beruflichen Wechsel vollzogen, um bessere Beschäftigungs- und Work-Life-Balance-Möglichkeiten zu haben, und Jahre später bin ich fest davon überzeugt, dass dies die richtige Entscheidung war.<br /><br />&emsp;Ich habe das Gefühl, dass ich mich in einer fast einzigartigen Position befinde, da ich jetzt meine wissenschaftlichen und analytischen Fähigkeiten nutzen kann, um Websites (wie mein CSS-Parsing-Tool <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) zu entwickeln, die andere Leute oder sogar Teams nicht kosteneffizient gestalten könnten produzieren, da für solche Standorte mehrere Mitarbeiter mit unterschiedlichen Fähigkeiten erforderlich wären. Die <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">Earthquake Hazards Program API</a>, die eine Datenbank mit Hunderten von Jahren abfragt von seismischen Daten bietet eine solche Gelegenheit. Obwohl dieses Programm eines der ganz <i>wenigen</i> ist, das einen Benutzeroberflächen-Wrapper für die API bietet (gefunden <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">hier</a>), wodurch der Zugriff auf die API erheblich einfacher wird. Es können jedoch noch mehrere Mehrwertverbesserungen hinzugefügt werden, einschließlich Zugriff in mehreren Sprachen (Englisch, Spanisch, Französisch und Italienisch ab Januar 2024). Dies war das Ziel der von mir entwickelten Benutzeroberfläche für den Quake-Katalog.'
  },
  en: {
    heading: 'About',
    content: 'My name is Dr. David Partyka, and I created Quake Catalog UI. Although I was trained for several years as a chemist, and even earned a PhD from a top university and published over 20 papers, I transitioned into web development after the last engineering company I worked for (heavily-focused on chemistry) folded in 2011. I made this career transition for better employment and work-life balance opportunities, and years later, I wholeheartedly believe this was the correct choice.<br /><br />&emsp;I feel that I am in an almost unique position in that I can now use my scientific and analytical skills to develop websites (such as my CSS parsing tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) that other people, or even teams, would not be able to cost-efficiently produce because such sites would require multiple personnel with different skill sets. The <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">Earthquake Hazards Program API</a>, which queries a database containing hundreds of years of seismic data, presents one such opportunity. Although this program is one of the very <i>few</i> to present a user interface wrapper for the API (found <a href="https://earthquake.usgs.gov/earthquakes/search/" target="_blank">here</a>), making access of the API much easier, there are still multiple value-added enhancements that can be added, including access in multiple languages (English, Spanish, French, and Italian as of January 2024). This was the goal of the Quake Catalog UI I developed.'
  },
  es: {
    heading: 'Acerca de',
    content: 'Mi nombre es Dr. David Partyka y creé la interfaz de usuario de Quake Catalog. Aunque me formé como químico durante varios años, e incluso obtuve un doctorado de una de las mejores universidades y publiqué más de 20 artículos, hice la transición al desarrollo web después de que la última empresa de ingeniería para la que trabajé (muy centrada en la química) cerró en 2011. Hice esta transición profesional para obtener mejores oportunidades de empleo y equilibrio entre vida personal y laboral, y años después, creo sinceramente que esta fue la elección correcta.<br /><br />&emsp;Siento que estoy en una posición casi única en ese sentido. Ahora puedo utilizar mis habilidades científicas y analíticas para desarrollar sitios web (como mi herramienta de análisis de CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>). que otras personas, o incluso equipos, no podrían producir de manera rentable porque dichos sitios requerirían mucho personal con diferentes habilidades. La <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API del Programa de Riesgos Sísmicos</a>, que consulta una base de datos que contiene cientos de años de datos sísmicos, presenta una de esas oportunidades. Aunque este programa es uno de los <i>pocos</i> que presenta un contenedor de interfaz de usuario para la API (encontrado <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">aquí</a>), lo que hace que el acceso a la API sea mucho más fácil, todavía se pueden agregar múltiples mejoras de valor agregado, incluido el acceso en varios idiomas (inglés, español, francés e italiano a partir de enero de 2024). Este era el objetivo de la interfaz de usuario de Quake Catalog que desarrollé.'
  },
  fr: {
    heading: 'À propos',
    content: 'Je m\'appelle le Dr David Partyka et j\'ai créé l\'interface utilisateur de Quake Catalog. Bien que j\'aie été formé pendant plusieurs années en tant que chimiste, et que j\'ai même obtenu un doctorat dans une grande université et publié plus de 20 articles, je me suis tourné vers le développement Web après la fermeture de la dernière société d\'ingénierie pour laquelle j\'ai travaillé (fortement axée sur la chimie) en 2011. J\'ai fait cette transition de carrière pour de meilleures opportunités d\'emploi et d\'équilibre travail-vie personnelle, et des années plus tard, je crois de tout cœur que c\'était le bon choix.<br /><br />&emsp;Je sens que je suis dans une position presque unique dans ce domaine. Je peux désormais utiliser mes compétences scientifiques et analytiques pour développer des sites Web (comme mon outil d\'analyse CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que d\'autres personnes, ou même des équipes, ne seraient pas en mesure de produire de manière rentable car de tels sites nécessiteraient plusieurs personnes possédant des compétences différentes. L\'<a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API du programme sur les risques sismiques</a>, qui interroge une base de données contenant des centaines d\'années des données sismiques, présente une telle opportunité. Bien que ce programme soit l\'un des très <i>rares</i> à présenter un wrapper d\'interface utilisateur pour l\'API (trouvé <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">ici</a>), ce qui rend l\'accès à l\'API beaucoup plus facile, mais plusieurs améliorations à valeur ajoutée peuvent encore être ajoutées, y compris l\'accès en plusieurs langues (anglais, espagnol, français et italien à partir de janvier 2024). C\'était l\'objectif de l\'interface utilisateur de Quake Catalog que j\'ai développée.'
  },
  hi: {
    heading: 'के बारे में',
    content: 'मेरा नाम डॉ. डेविड पार्टीका है और मैंने क्वेक कैटलॉग यूआई बनाया है। हालाँकि मुझे एक रसायनज्ञ के रूप में कई वर्षों तक प्रशिक्षित किया गया था, और यहां तक ​​​​कि एक शीर्ष विश्वविद्यालय से पीएचडी भी हासिल की थी और 20 से अधिक शोधपत्र प्रकाशित किए थे, 2011 में जिस आखिरी इंजीनियरिंग कंपनी (रसायन विज्ञान पर अत्यधिक ध्यान केंद्रित) के लिए मैंने काम किया था, उसके बंद होने के बाद मैंने वेब विकास में बदलाव किया। मैंने बेहतर रोजगार और कार्य-जीवन संतुलन के अवसरों के लिए यह करियर परिवर्तन किया, और वर्षों बाद, मैं पूरे दिल से मानता हूं कि यह सही विकल्प था।<br /><br />&emsp;मुझे लगता है कि मैं लगभग एक अद्वितीय स्थिति में हूं कि अब मैं वेबसाइट विकसित करने के लिए अपने वैज्ञानिक और विश्लेषणात्मक कौशल का उपयोग कर सकता हूं (जैसे कि मेरा सीएसएस पार्सिंग टूल, <a href="https://cssburner.com" target="_blank" rel=”noreferrer”>CSSBurner</a>) जिसे अन्य लोग, या यहां तक ​​कि टीमें, लागत-कुशलतापूर्वक उत्पादन करने में सक्षम नहीं होंगी क्योंकि ऐसी साइटों को विभिन्न कौशल सेट वाले कई कर्मियों की आवश्यकता होगी। <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank rel="noreferrer">भूकंप खतरा कार्यक्रम एपीआई</a>, जो सैकड़ों वर्षों वाले डेटाबेस पर सवाल उठाता है भूकंपीय डेटा, एक ऐसा अवसर प्रस्तुत करता है। हालाँकि यह प्रोग्राम एपीआई के लिए यूजर इंटरफेस रैपर प्रस्तुत करने वाले कुछ <i>कुछ</i> में से एक है (पाया गया <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">यहां</a>), एपीआई की पहुंच को बहुत आसान बनाते हुए, अभी भी कई मूल्यवर्धित संवर्द्धन जोड़े जा सकते हैं, जिनमें कई भाषाओं में पहुंच शामिल है (जनवरी 2024 तक अंग्रेजी, स्पेनिश, फ्रेंच और इतालवी) . मेरे द्वारा विकसित क्वेक कैटलॉग यूआई का लक्ष्य यही था।'
  },
  it: {
    heading: 'Di',
    content: 'Mi chiamo Dr. David Partyka e ho creato l\'interfaccia utente di Quake Catalog. Sebbene abbia studiato per diversi anni come chimico e abbia anche conseguito un dottorato di ricerca in una delle migliori università e pubblicato oltre 20 articoli, sono passato allo sviluppo web dopo che l\'ultima società di ingegneria per cui ho lavorato (fortemente focalizzata sulla chimica) ha chiuso i battenti nel 2011. Ho intrapreso questa transizione professionale per migliori opportunità di lavoro e di equilibrio tra lavoro e vita privata e, anni dopo, credo fermamente che questa sia stata la scelta corretta.<br /><br />&emsp;Sento di trovarmi in una posizione quasi unica in questo Ora posso utilizzare le mie capacità scientifiche e analitiche per sviluppare siti web (come il mio strumento di analisi CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) che altre persone, o addirittura team, non sarebbero in grado di produrre in modo economicamente efficiente perché tali siti richiederebbero più personale con competenze diverse. L\'<a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API del programma Earthquake Hazards</a>, che interroga un database contenente centinaia di anni dei dati sismici, presenta una di queste opportunità. Sebbene questo programma sia uno dei pochissimi <i>pochi</i> a presentare un wrapper dell\'interfaccia utente per l\'API (trovato <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">qui</a>), rendendo l\'accesso all\'API molto più semplice, è possibile aggiungere ancora numerosi miglioramenti a valore aggiunto, incluso l\'accesso in più lingue (inglese, spagnolo, francese e italiano a partire da gennaio 2024). Questo era l\'obiettivo dell\'interfaccia utente del catalogo Quake che ho sviluppato.'
  },
  ja: {
    heading: 'について',
    content: '私の名前は David Partyka 博士です。Quake Catalog UI を作成しました。私は化学者として数年間訓練を受け、一流大学で博士号を取得し、20 本以上の論文を発表しましたが、最後に勤めていたエンジニアリング会社 (化学に重点を置いていた) が 2011 年に倒産した後、Web 開発に移行しました。私はより良い雇用とワークライフバランスの機会を求めてこの転職をしましたが、数年後、これが正しい選択だったと心から信じています。<br /><br />&emsp;私は、自分の科学的および分析的スキルを利用して、他の人やチームですらコスト効率よくできない ウェブサイト (CSS 解析ツールの <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a> など) を開発できるという点で、ほぼユニークな立場にあると感じています。そのような現場では、異なるスキルセットを持つ複数の担当者が必要になるためです。 <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">地震災害プログラム API</a>。数百年分のデータベースをクエリします。地震データの分析は、そのような機会の 1 つを提供します。このプログラムは、API のユーザー インターフェイス ラッパーを提供する非常に<i>数少ない</i>プログラムの 1 つですが (<a href="https://earthquake.usgs.gov/earthquakes/search/" target="_blank">こちら</a>)、API へのアクセスがはるかに簡単になりましたが、複数の言語 (2024 年 1 月現在、英語、スペイン語、フランス語、イタリア語) でのアクセスなど、追加できる付加価値の拡張機能が多数あります。これが私が開発した Quake Catalog UI の目標でした。'
  },
  ko: {
    heading: '에 대한',
    content: '제 이름은 Dr. David Partyka이고 Quake Catalog UI를 만들었습니다. 나는 몇 년 동안 화학자 훈련을 받고 일류 대학에서 박사 학위를 취득하고 20개 이상의 논문을 발표했지만, 2011년에 내가 일했던 마지막 엔지니어링 회사(화학에 중점을 두는)가 문을 닫은 후 웹 개발로 전환했습니다. 저는 더 나은 취업과 일과 삶의 균형을 위해 이 직업 전환을 했고, 몇 년이 지난 지금은 이것이 올바른 선택이었다고 진심으로 믿습니다.<br /><br />&emsp;나는 이제 과학적이고 분석적인 기술을 사용하여 다른 사람이나 심지어 팀이 비용 효율적으로 만들 수 없는 웹 사이트(예: CSS 구문 분석 도구, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>)를 개발할 수 있다는 점에서 거의 독특한 위치에 있다고 생각합니다. 그러한 현장에는 다양한 기술을 가진 여러 인력이 필요하기 때문입니다. 수백 년의 데이터를 포함하는 데이터베이스를 쿼리하는 <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">지진 위험 프로그램 API</a> 지진 데이터는 그러한 기회 중 하나를 제공합니다. 이 프로그램은 API에 대한 사용자 인터페이스 래퍼를 제공하는 <i>몇 안 되는</i> 프로그램 중 하나이지만(<a href="https://earthquake.usgs.gov/earthquakes/search/" target="_blank">여기</a>) API에 훨씬 더 쉽게 액세스할 수 있지만 여러 언어(2024년 1월 현재 영어, 스페인어, 프랑스어, 이탈리아어)로의 액세스를 포함하여 추가할 수 있는 여러 가지 부가 가치 향상 기능이 여전히 있습니다. 이것이 제가 개발한 Quake Catalog UI의 목표였습니다.'
  },
  ru: {
    heading: 'О',
    content: 'Меня зовут доктор Дэвид Партика, и я создал пользовательский интерфейс каталога Quake. Хотя я несколько лет учился на химика, даже получил докторскую степень в ведущем университете и опубликовал более 20 статей, я перешел в веб-разработку после того, как последняя инжиниринговая компания, в которой я работал (специально ориентированная на химию), закрылась в 2011 году. Я совершил этот карьерный переход, чтобы улучшить возможности трудоустройства и найти баланс между работой и личной жизнью, и спустя годы я искренне верю, что это был правильный выбор.<br /><br />&emsp;Я чувствую, что нахожусь в почти уникальном положении: теперь я могу использовать свои научные и аналитические навыки для разработки веб-сайтов (таких как мой инструмент анализа CSS <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>), которые другие люди или даже команды не смогут создать экономически эффективно. производить, потому что на таких объектах потребуется несколько сотрудников с разными навыками. <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API программы по опасностям землетрясений</a>, который запрашивает базу данных, содержащую сотни лет. сейсмических данных представляет одну из таких возможностей. Хотя эта программа является одной из очень <i>немногих</i>, представляющих оболочку пользовательского интерфейса для API (найдена <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">здесь</a>), что значительно упрощает доступ к API, но по-прежнему можно добавить множество дополнительных улучшений, включая доступ на нескольких языках (английском, испанском, французском и итальянском по состоянию на январь 2024 года). Это была цель пользовательского интерфейса каталога Quake, который я разработал.'
  },
  zh: {
    heading: '關於',
    content: '我的名字是 David Partyka 博士，我創建了 Quake Catalog UI。儘管我接受了多年的化學家培訓，甚至從頂尖大學獲得了博士學位，並發表了20 多篇論文，但在我工作的最後一家工程公司（主要專注於化學）於2011 年倒閉後，我轉向了Web 開發。我進行職業轉型是為了獲得更好的就業和工作與生活平衡的機會，多年後，我全心全意地相信這是正確的選擇。<br /><br />&emsp;我覺得我處於一個幾乎獨特的位置，因為我現在可以利用我的科學和分析技能來開發網站（例如我的 CSS 解析工具 <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>）而其他人甚至團隊無法經濟高效地開發網站因為這些網站需要多名具有不同技能的人員。 <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">Earthquake Hazards Program API</a>，查詢包含數百年歷史的資料庫地震數據提供了這樣一個機會。儘管此程式是極少數為 API 提供使用者介麵包裝的程式（發現 <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">此處</a> ），使API 的訪問變得更加容易，仍然可以添加多個增值增強功能，包括多種語言的訪問（截至2024 年1 月的英語、西班牙語、法語和意大利語） 。這就是我開發的 Quake Catalog UI 的目標。'
  }
};

export default TEXT_MAP;
