export const TEXT_MAP = {
  en: {
    heading: 'About',
    content: 'My name is Dr. David Partyka, and I created Quake Catalog UI. Although I was trained for several years as a chemist, and even earned a PhD from a top university and published over 20 papers, I transitioned into web development after the last engineering company I worked for (heavily-focused on chemistry) folded in 2011. I made this career transition for better employment and work-life balance opportunities, and years later, I wholeheartedly believe this was the correct choice.<br /><br />&emsp;I feel that I am in an almost unique position in that I can now use my scientific and analytical skills to develop websites (such as my CSS parsing tool, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) that other people, or even teams, would not be able to cost-efficiently produce because such sites would require multiple personnel with different skill sets. The <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">Earthquake Hazards Program API</a>, which queries a database containing hundreds of years of seismic data, presents one such opportunity. Although this program is one of the very <i>few</i> to present a user interface wrapper for the API (found <a href="https://earthquake.usgs.gov/earthquakes/search/" target="_blank">here</a>), making access of the API much easier, there are still multiple value-added enhancements that can be added, including access in multiple languages (English, Spanish, French, and Italian as of January 2024). This was the goal of the Quake Catalog UI I developed.'
  },
  es: {
    heading: 'Acerca de',
    content: 'Mi nombre es Dr. David Partyka y creé la interfaz de usuario de Quake Catalog. Aunque me formé como químico durante varios años, e incluso obtuve un doctorado de una de las mejores universidades y publiqué más de 20 artículos, hice la transición al desarrollo web después de que la última empresa de ingeniería para la que trabajé (muy centrada en la química) cerró en 2011. Hice esta transición profesional para obtener mejores oportunidades de empleo y equilibrio entre vida personal y laboral, y años después, creo sinceramente que esta fue la elección correcta.<br /><br />&emsp;Siento que estoy en una posición casi única en ese sentido. Ahora puedo utilizar mis habilidades científicas y analíticas para desarrollar sitios web (como mi herramienta de análisis de CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>). que otras personas, o incluso equipos, no podrían producir de manera rentable porque dichos sitios requerirían mucho personal con diferentes habilidades. La <a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API del Programa de Riesgos Sísmicos</a>, que consulta una base de datos que contiene cientos de años de datos sísmicos, presenta una de esas oportunidades. Aunque este programa es uno de los <i>pocos</i> que presenta un contenedor de interfaz de usuario para la API (encontrado <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">aquí</a>), lo que hace que el acceso a la API sea mucho más fácil, todavía se pueden agregar múltiples mejoras de valor agregado, incluido el acceso en varios idiomas (inglés, español, francés e italiano a partir de enero de 2024). Este era el objetivo de la interfaz de usuario de Quake Catalog que desarrollé.'
  },
  fr: {
    heading: 'À propos',
    content: 'Je m\'appelle le Dr David Partyka et j\'ai créé l\'interface utilisateur de Quake Catalog. Bien que j\'aie été formé pendant plusieurs années en tant que chimiste, et que j\'ai même obtenu un doctorat dans une grande université et publié plus de 20 articles, je me suis tourné vers le développement Web après la fermeture de la dernière société d\'ingénierie pour laquelle j\'ai travaillé (fortement axée sur la chimie) en 2011. J\'ai fait cette transition de carrière pour de meilleures opportunités d\'emploi et d\'équilibre travail-vie personnelle, et des années plus tard, je crois de tout cœur que c\'était le bon choix.<br /><br />&emsp;Je sens que je suis dans une position presque unique dans ce domaine. Je peux désormais utiliser mes compétences scientifiques et analytiques pour développer des sites Web (comme mon outil d\'analyse CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) que d\'autres personnes, ou même des équipes, ne seraient pas en mesure de produire de manière rentable car de tels sites nécessiteraient plusieurs personnes possédant des compétences différentes. L\'<a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API du programme sur les risques sismiques</a>, qui interroge une base de données contenant des centaines d\'années des données sismiques, présente une telle opportunité. Bien que ce programme soit l\'un des très <i>rares</i> à présenter un wrapper d\'interface utilisateur pour l\'API (trouvé <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">ici</a>), ce qui rend l\'accès à l\'API beaucoup plus facile, mais plusieurs améliorations à valeur ajoutée peuvent encore être ajoutées, y compris l\'accès en plusieurs langues (anglais, espagnol, français et italien à partir de janvier 2024). C\'était l\'objectif de l\'interface utilisateur de Quake Catalog que j\'ai développée.'
  },
  it: {
    heading: 'Di',
    content: 'Mi chiamo Dr. David Partyka e ho creato l\'interfaccia utente di Quake Catalog. Sebbene abbia studiato per diversi anni come chimico e abbia anche conseguito un dottorato di ricerca in una delle migliori università e pubblicato oltre 20 articoli, sono passato allo sviluppo web dopo che l\'ultima società di ingegneria per cui ho lavorato (fortemente focalizzata sulla chimica) ha chiuso i battenti nel 2011. Ho intrapreso questa transizione professionale per migliori opportunità di lavoro e di equilibrio tra lavoro e vita privata e, anni dopo, credo fermamente che questa sia stata la scelta corretta.<br /><br />&emsp;Sento di trovarmi in una posizione quasi unica in questo Ora posso utilizzare le mie capacità scientifiche e analitiche per sviluppare siti web (come il mio strumento di analisi CSS, <a href="https://cssburner.com" target="_blank" rel="noreferrer">CSSBurner</a>) che altre persone, o addirittura team, non sarebbero in grado di produrre in modo economicamente efficiente perché tali siti richiederebbero più personale con competenze diverse. L\'<a href="https://www.usgs.gov/programs/earthquake-hazards" target="_blank" rel="noreferrer">API del programma Earthquake Hazards</a>, che interroga un database contenente centinaia di anni dei dati sismici, presenta una di queste opportunità. Sebbene questo programma sia uno dei pochissimi <i>pochi</i> a presentare un wrapper dell\'interfaccia utente per l\'API (trovato <a href="https://earthquake.usgs.gov/earthquakes/search/" target=" _blank">qui</a>), rendendo l\'accesso all\'API molto più semplice, è possibile aggiungere ancora numerosi miglioramenti a valore aggiunto, incluso l\'accesso in più lingue (inglese, spagnolo, francese e italiano a partire da gennaio 2024). Questo era l\'obiettivo dell\'interfaccia utente del catalogo Quake che ho sviluppato.'
  }
};

export default TEXT_MAP;
